### PR TITLE
DIV-4826: Adding new template id

### PR DESCRIPTION
**Pull request by jvictorcf**
# Description

Including the Docmosis template information for the list with cases to be pronounced.

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Unit tests and manually by using CCD.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by qzhou-hmcts** [comment]
not test here?

**Comment by jvictorcf** [comment]
> Looks good but Integration tests missing

@ravinderpal, Unit tests should be enough for this. I've just written some.

**Comment by jvictorcf** [comment]
> not test here?

@qzhou-hmcts I've implemented the tests.

**Comment by vianvi** [comment]
no Integration Test?

**Comment by jvictorcf** [comment]
> no Integration Test? Please add the integration test, similar to
> https://github.com/hmcts/div-document-generator-client/tree/master/src/integrationTest/java/uk/gov/hmcts/reform/divorce

Hi @vianvi. We don't need new integration tests for this. There's no new integration, it's only a parameter change.

**Comment by vianvi** [comment]
> > no Integration Test? Please add the integration test, similar to
> > https://github.com/hmcts/div-document-generator-client/tree/master/src/integrationTest/java/uk/gov/hmcts/reform/divorce
> 
> Hi @vianvi. We don't need new integration tests for this. There's no new integration, it's only a parameter change.
> That's already covered by the functional tests.

I think functional tests are not clear enough  on what data we are passing and validating for dicument generation.

**Pull request merged**
